"""Reusable, in-memory SMTP delivery helpers for attendance reports."""

from __future__ import annotations

import smtplib
import socket
from email.message import EmailMessage
from pathlib import Path

import database

REPORT_FILENAME = "attendance_report.csv"
EMAIL_BODY = (
    "Please find attached the latest attendance report generated by the "
    "Smart Attendance System."
)


def generate_attendance_csv() -> Path:
    """Create the current report from SQLite and return its path.

    This deliberately regenerates the file on every send, so an older export
    can never be attached accidentally.
    """
    return database.export_to_csv()


def build_email(
    sender: str, recipient: str, subject: str, report: Path
) -> EmailMessage:
    """Build an attendance email with its CSV attachment."""
    if not report.is_file():
        raise FileNotFoundError("The attendance report CSV could not be created.")

    message = EmailMessage()
    message["From"] = sender
    message["To"] = recipient
    message["Subject"] = subject
    message.set_content(EMAIL_BODY)
    message.add_attachment(
        report.read_bytes(), maintype="text", subtype="csv", filename=REPORT_FILENAME
    )
    return message


def send_email(
    *,
    smtp_host: str,
    smtp_port: int,
    sender: str,
    app_password: str,
    message: EmailMessage,
) -> None:
    """Deliver an email with STARTTLS.  The password is never persisted or logged."""
    try:
        with smtplib.SMTP(smtp_host, smtp_port, timeout=20) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(sender, app_password)
            server.send_message(message)
    except (
        smtplib.SMTPAuthenticationError,
        smtplib.SMTPConnectError,
        smtplib.SMTPException,
        socket.gaierror,
        OSError,
        TimeoutError,
    ):
        # The UI maps these safely to user-facing errors without exposing secrets.
        raise
